---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: proxy
    owner: mohan
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy        
    spec: 
      containers:
        - name: mynginx
          image: nginx                   
...
