---
apiVersion: v1
kind: Pod
metadata:  
  name: httpd
  namespace: test-ns
  labels: 
    app: webserver
    author: mohan
spec: 
  containers: 
    - name: myhttpd
      image: httpd
      ports: 
       - containerPort: 80
         hostPort: 8080  


...
