---
apiVersion: v1
kind: Pod
metadata: 
 name: jenkins-pod
 labels: 
   app: ci-cd 
   created: mohan
spec: 
   containers: 
     - name: myjenkins
       image: jenkins/jenkins
       ports: 
        - containerPort: 8080
          hostPort: 7070

...
