---
apiVersion: v1
kind: Pod
metadata: 
 name: postgres-pod
 labels: 
   app: datbase
   owner: mohan
spec: 
  containers: 
    - name: mydb
      image: postgres
      env: 
        - name: POSTGRES_PASSWORD
          value: mohansai
        - name : POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb   


...
